name: Rust CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] # Also run on pushes to main after merge

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # Cache workspace-level target directory
          workspaces: ". -> target"

      - name: Build
        run: cargo build --verbose

      - name: Run tests and generate coverage report
        run: cargo llvm-cov --verbose --cobertura --output-path cobertura.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional: Usually not needed for public repos
          files: cobertura.xml
          fail_ci_if_error: true # Optional: Fail CI if Codecov upload fails 